# Generated by Django 5.1 on 2025-06-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='hospital_affiliation',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='is_available',
        ),
    ]
