# Generated by Django 5.1 on 2025-06-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctorprofile_user'),
        ('patients', '0006_alter_patientrequest_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_date', models.DateTimeField(auto_now_add=True, help_text='date of connection')),
                ('doctor', models.ForeignKey(help_text='doctor model', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(help_text='patient model', on_delete=django.db.models.deletion.CASCADE, to='patients.patientrecord')),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
