# Generated by Django 4.2.23 on 2025-07-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_delete_appointment'),
        ('doctor', '0004_patientslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('doc_meeting_link', models.URLField(blank=True)),
                ('pat_meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hms_room_id', models.CharField(blank=True, max_length=128, null=True)),
                ('hms_room_name', models.CharField(blank=True, max_length=128, null=True)),
                ('hms_room_desc', models.CharField(blank=True, max_length=120, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientrecord')),
            ],
        ),
    ]
