# Generated by Django 5.1 on 2025-06-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('chronic_conditions', models.JSONField(blank=True, null=True)),
                ('blood_type', models.CharField(max_length=3, null=True)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('body_temperature', models.FloatField(null=True)),
                ('heart_rate', models.IntegerField(null=True)),
                ('respiratory_rate', models.IntegerField(null=True)),
            ],
        ),
    ]
