# Generated by Django 5.1 on 2025-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='body_temperature',
            field=models.FloatField(help_text='Body temperature in Celsius', null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='chronic_conditions',
            field=models.JSONField(blank=True, help_text='List of chronic medical conditions', null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='emergency_contact_number',
            field=models.CharField(help_text='Emergency contact phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='heart_rate',
            field=models.IntegerField(help_text='Heart rate in beats per minute', null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='height',
            field=models.FloatField(help_text='Height in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='respiratory_rate',
            field=models.IntegerField(help_text='Respiratory rate in breaths per minute', null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='uid',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier for the patient record', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='weight',
            field=models.FloatField(help_text='Weight in kilograms', null=True),
        ),
    ]
