# Generated by Django 5.1 on 2025-06-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctorprofile_hospital_affiliation_and_more'),
        ('patients', '0003_alter_patientrecord_body_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text="Select the patient's blood type", max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the request', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the request was created')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the request', null=True)),
                ('doctor', models.ForeignKey(help_text='Doctor to whom the request is made', on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(help_text='Patient making the request', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='patients.patientrecord')),
            ],
            options={
                'verbose_name': 'Patient Request',
                'verbose_name_plural': 'Patient Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
