# Generated by Django 5.1 on 2025-06-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patientrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='request_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', help_text='Current status of the request', max_length=20),
        ),
    ]
