# Generated by Django 5.1 on 2025-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_medication_doctor_alter_medication_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='name',
            field=models.CharField(default='', help_text='name of the medicine', max_length=50),
        ),
    ]
