# Generated by Django 5.1 on 2025-06-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_medication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='fequency',
            field=models.CharField(default='', help_text='eg. Twice a day', max_length=100),
        ),
    ]
