# Generated by Django 5.1 on 2025-06-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_medication_fequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='fequency',
            new_name='frequency',
        ),
    ]
