# Generated by Django 5.1 on 2025-06-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_rename_fequency_medication_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the report', max_length=200)),
                ('report_type', models.CharField(choices=[('BLOOD_TEST', 'Blood Test'), ('X_RAY', 'X-Ray'), ('MRI', 'MRI'), ('CT_SCAN', 'CT Scan'), ('ULTRASOUND', 'Ultrasound'), ('ECG', 'ECG'), ('ECHO', 'Echocardiogram'), ('BIOPSY', 'Biopsy'), ('PATHOLOGY', 'Pathology'), ('OTHER', 'Other')], help_text='Type of medical report', max_length=20)),
                ('report_date', models.DateField(help_text='Date when the test/procedure was conducted')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, help_text='Date when report was uploaded')),
                ('file', models.FileField(help_text='Upload the report file (PDF, Image, etc.)', upload_to='patient_reports/')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about the report', null=True)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal'), ('CRITICAL', 'Critical'), ('PENDING', 'Pending Review')], default='PENDING', help_text='Status of the report', max_length=20)),
                ('lab_facility', models.CharField(blank=True, help_text='Laboratory or facility where test was conducted', max_length=200, null=True)),
                ('doctor_notes', models.TextField(blank=True, help_text='Notes from doctor reviewing the report', null=True)),
                ('is_shared_with_doctors', models.BooleanField(default=True, help_text='Whether this report is shared with connected doctors')),
                ('patient', models.ForeignKey(help_text='Patient who owns this report', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patientrecord')),
            ],
            options={
                'verbose_name': 'Patient Report',
                'verbose_name_plural': 'Patient Reports',
                'ordering': ['-report_date', '-uploaded_date'],
            },
        ),
    ]
