# Generated by Django 5.1 on 2025-06-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_report_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_shared_with_doctors',
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
    ]
