# Generated by Django 5.1 on 2025-06-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_remove_report_is_shared_with_doctors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor_notes',
        ),
    ]
