# Generated by Django 4.2.23 on 2025-07-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='meeting_link',
            new_name='doc_meeting_link',
        ),
        migrations.AddField(
            model_name='appointment',
            name='hms_room_desc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hms_room_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hms_room_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pat_meeting_link',
            field=models.URLField(blank=True),
        ),
    ]
