# Generated by Django 4.2.23 on 2025-07-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_rename_meeting_link_appointment_doc_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
