# Generated by Django 4.2.23 on 2025-07-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_appointment_task_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
